//! Interactive LLM dialogue test with real Ollama inference.
//!
//! Chat with an NPC blacksmith in your terminal. Type messages and get
//! intelligent responses generated by llama3.2:1b via Ollama.
//!
//! Prerequisites: `ollama serve` && `ollama pull llama3.2:1b`
//!
//! Usage:
//!   cargo run -p memz-voice --example test_llm

use memz_voice::llm::{DialogueLlm, LlmConfig, NpcContext};
use memz_voice::conversation::ConversationHistory;
use std::io::{self, Write};

fn main() -> anyhow::Result<()> {
    env_logger::init();

    println!("=== Interactive NPC Dialogue Test ===\n");

    let mut llm = DialogueLlm::new(LlmConfig {
        model_name: "llama3.2:1b".to_string(),
        max_tokens: 80,
        ..LlmConfig::default()
    })?;

    let npc = NpcContext {
        name: "Thorin".to_string(),
        profession: "Blacksmith".to_string(),
        location: "Ironforge".to_string(),
        faction: "Mountain Clan".to_string(),
        personality: "Gruff but kind-hearted, proud of craft".to_string(),
        mood: "friendly".to_string(),
        knowledge: String::new(),
        player_sentiment: "curious stranger".to_string(),
    };

    let mut history = ConversationHistory::new(1, 6);

    println!("NPC: Thorin the Blacksmith (friendly)");
    println!("Type your message (or 'quit' to exit)\n");

    loop {
        print!("You: ");
        io::stdout().flush()?;

        let mut input = String::new();
        io::stdin().read_line(&mut input)?;
        let player_input = input.trim();

        if player_input.is_empty() { continue; }
        if player_input.eq_ignore_ascii_case("quit") { break; }

        let start = std::time::Instant::now();
        match llm.generate_response(&npc, player_input, Some(&history)) {
            Ok(response) => {
                let elapsed = start.elapsed();
                println!("🤖 Thorin ({}ms): {}\n", elapsed.as_millis(), response);
                history.add_exchange(player_input.to_string(), response);
            }
            Err(e) => println!("❌ Error: {}\n", e),
        }
    }

    println!("Farewell, traveler!");
    Ok(())
}
